### ISSUE TITLE
Customs Dial method

### ISSUE THREAD

**Issue by tungphan899** [OmarTariq612/socks-server#1]
Hello,
Can you please add something more on this project ?
1. Use customs Dial method, to forward request, look like go-socks5, they have a customs config, and i can set a custom Dial method.
      conf := socks5.Config{
		Dial: func(ctx context.Context, network, addr string) (net.Conn, error) {
			return sshConn.Dial(network, addr)
		},
		Resolver: resolver,
	}
As you can see, i can use SSH as a Dial Method.
2. Fix to use customs DNS server. Or at least disable any website can get my dns, because its go wrong. 
Examples : 
My SSH has IP Address : 123.123.123.123
My Ubuntu Server IP : 139.90.60.30
On ubuntu server, i open a ssh connection, open a port and listen on that port. Examples : 139.90.60.30:1080
On my client, use 139.90.60.30:1080 as a socks5. The socks5 IP Address is 123.123.123.123. Website can get that ip, but the dns go wrong, dns record show my ubuntu ip address : 139.90.60.30
I want to change the DNS record to 123.123.123.123. Or at least, disable it, and no one can get it 

Thanks you verry much, and hope you have a nice day

**Comment by OmarTariq612** [comment]
Hello,
1. I've added custom socks config so you can now use a custom Dial function, ex:

sshConfig := &ssh.ClientConfig{
    User:            "user",
    Auth:            []ssh.AuthMethod{ssh.Password("password")},
    HostKeyCallback: ssh.InsecureIgnoreHostKey(),
}
sshClient, err := ssh.Dial("tcp", "192.168.1.10:22", sshConfig)
defer sshClient.Close()
socksConfig := &utils.Config{
    Dial: func(ctx context.Context, network, addr string) (net.Conn, error) {
	    return sshClient.Dial(network, addr)
    },
}
s := server.NewSocksServer(socksConfig)

2. You can now specify a dns server using the binary arguments or programmatically:
`./socks-server --bind 192.168.1.5:1080 --dns 8.8.8.8:53`
or
socksConfig := &utils.Config{
    Resolv: utils.NewCustomResolver("8.8.8.8:53"),
}
s := server.NewSocksServer(socksConfig)

If this didn't solve your issue then can you explain the dns issue more clearly ?
- Which socks5 client are you using ?
- Which exact ssh commands you are using to tunnel the traffic ?
- Which website are you using to get the dns test results ?

Thanks, and have a nice day.

**Comment by tungphan899** [comment]
Thanks you verry much, you make my life easier.
I new in golang so i cant make something difficult.
Once again, thanks you verry much.
